Set vQvd_Nombre = L1_MYSQL_factsales;

[$(vQvd_Nombre)]:
SELECT SalesKey,
	DateKey,
	channelKey,
	StoreKey,
	ProductKey,
	PromotionKey,
	CurrencyKey,
	UnitCost,
	UnitPrice,
	SalesQuantity,
	ReturnQuantity,
	ReturnAmount,
	DiscountQuantity,
	DiscountAmount,
	TotalCost,
	SalesAmount,
	ETLLoadID,
	LoadDate,
	UpdateDate
FROM spanish.factsales;

Store [$(vQvd_Nombre)] into [$(vR_QvdExt)$(vQvd_Nombre).qvd] (qvd);
Drop Table [$(vQvd_Nombre)];